# Generated by Django 3.1.7 on 2021-03-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now=True)),
                ('save_time', models.DurationField(null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.seriesvideo')),
                ('subuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subuser')),
            ],
            options={
                'db_table': 'watched_movies',
            },
        ),
    ]
