# Generated by Django 3.1.7 on 2021-03-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_service', models.BooleanField()),
                ('service_date', models.DateField(null=True)),
                ('poster1', models.CharField(max_length=500)),
                ('poster2', models.CharField(max_length=500, null=True)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('recommended', models.IntegerField()),
                ('released', models.DateField()),
                ('duration', models.DurationField()),
                ('preview', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_service', models.BooleanField()),
                ('service_date', models.DateField(null=True)),
                ('poster1', models.CharField(max_length=500)),
                ('poster2', models.CharField(max_length=500, null=True)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('recommended', models.IntegerField()),
                ('released', models.DateField()),
            ],
            options={
                'db_table': 'serieses',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='SeriesVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('preview', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.series')),
            ],
            options={
                'db_table': 'series_videos',
            },
        ),
        migrations.CreateModel(
            name='SeriesTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.series')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.tag')),
            ],
            options={
                'db_table': 'series_tags',
            },
        ),
        migrations.CreateModel(
            name='SeriesProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_actor', models.BooleanField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.producer')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.series')),
            ],
            options={
                'db_table': 'series_producers',
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.tag')),
            ],
            options={
                'db_table': 'movie_tags',
            },
        ),
        migrations.CreateModel(
            name='MovieProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_actor', models.BooleanField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.producer')),
            ],
            options={
                'db_table': 'movie_producers',
            },
        ),
    ]
